WIP better ui
dtu-qmcm/enzax pull request #29
Opened 2024-11-27 11:21 UTC by teddygroves

Checklist:

- [ ] tests pass
- [ ] `README.md` up to date
- [ ] docs up to date
- [ ] link to any relevant issues

2024-11-28 13:54 UTC, teddygroves commented
Now the example model tests pass!

2024-11-28 16:15 UTC, teddygroves commented
Now all the tests pass!

2024-12-11 09:56 UTC, AlberteSloth requested changes

2024-12-11 09:56 UTC, AlberteSloth commented on src/enzax/kinetic_model.py
>      balanced_ids: PyTree
Delete this line

2024-12-11 09:56 UTC, AlberteSloth commented on src/enzax/kinetic_model.py
>          self,
change "self.balanced_ids" to "self.structure.balanced_species"

2024-12-11 14:44 UTC, teddygroves commented
Oops, thanks @AlberteSloth!

2024-12-11 15:58 UTC, teddygroves commented on src/enzax/examples/linear.py
> +    log_ki={"r1": jnp.array([]), "r2": jnp.array([1.0]), "r3": jnp.array([])},
currently it just has to agree with the order of `balanced_species`

2024-12-13 10:32 UTC, NicholasCowie approved these changes
LGTM!

2024-12-13 13:57 UTC, merged